[[customizations.filesystem]]
mountpoint = "/var/tmp"
minsize = "1 GiB"

[[customizations.filesystem]]
mountpoint = "/var/log"
minsize = "10 GiB"

[[customizations.filesystem]]
mountpoint = "/var/log/audit"
minsize = "10 GiB"

[[customizations.filesystem]]
mountpoint = "/var"
minsize = "10 GiB"

[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"